### ISSUE TITLE
Shared servers? 

### ISSUE THREAD

**Issue by fkick** [ilyaz/PlexDownloader#8]
Any way to pull from shared myplex servers? Sections are usually the same number but the server if would be different. Thanks!

**Comment by ilyaz** [comment]
I have added preliminary support for this. Let me know if it works for you. Thanks!

**Comment by fkick** [comment]
After downloading the new version I'm unable to get the app started and I think it has to do with the web server. My log from the terminal is below:

Starting PlexDownloader Web Manager...
Starting Plex Scraper...
PlexDownloader - v0.04
Using cached myPlex token.
0 TV Shows Found in Your Wanted List...
Something went wrong: [Errno socket error] [Errno 61] Connection refused
Plex Download failed at 2015-04-10 07:37:22
Retrying in 600 Seconds...
PlexScraper - v0.01
Using cached myPlex token.
Plex Scraper completed at 2015-04-10 07:37:22
Sleeping 1200 Seconds...
Using cached myPlex token.
Traceback (most recent call last):
  File "webui.py", line 179, in <module>
    tvShowSearchWeb()
  File "webui.py", line 164, in tvShowSearchWeb
    website = urllib.urlopen(tvhttp)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 345, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 61] Connection refused

**Comment by drwilco** [comment]
Is the server you're connecting to up? The error there is "connection
refused", which is usually because the server isn't running. (or the
address is wrong.)

**Comment by fkick** [comment]
Sorry it's been a long while, but I've finally had time to swing back to this little project and had a quick question in regards to your myplex and sharing implementation. I've had plexdownloader working solid for local server content and I've been very happy. 

As I'm trying to get shared content working (both myplex and shared values are set to enable in user.ini) I'm thinking perhaps I'm using the wrong value for plexurl. To get local content to work I've always had my lan ip of my plex server in there. However, I don't see any shared content at all. If I use "https://plex.tv" as the plexurl that just fails out. What should be the value in the plexurl to allow for accessing content on a shared plex server?

Thanks!

EDIT: NM, I was able to obtain the remote server IP through the plex web interface and use that as the plexurl for PlexDownloader. It's working like a charm now. Thanks!

**Comment by encodes1** [comment]
how did you find the remote address?
